-- Seed data: 40 cars + content + blog (run AFTER schema.sql)

-- ===== CARS =====

insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('maruti-wagon-r','Maruti Wagon R','Hatchback','2026',4,1,'CNG','Manual',1800,'','',0) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('maruti-celerio','Maruti Celerio','Hatchback','2023',4,1,'CNG / Petrol','Manual',1800,'','',1) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('maruti-swift-dzire','Maruti Swift Dzire','Sedan','2026',4,2,'CNG','Manual',1800,'','/images/cars/maruti-swift-dzire.png',2) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('hyundai-aura','Hyundai Aura','Sedan','2025',4,2,'CNG','Manual',1800,'','',3) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('honda-city','Honda City','Sedan','2018',4,2,'Petrol','Automatic',2200,'','',4) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('toyota-corolla-altis','Toyota Corolla Altis','Sedan','2017',5,2,'CNG / Petrol','Manual',2000,'','',5) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('tata-nexon','Tata Nexon','Compact SUV','2025',5,2,'CNG / Petrol','Manual',2000,'','/images/cars/tata-nexon.png',6) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('maruti-brezza','Maruti Brezza','Compact SUV','2024',5,2,'Petrol','Manual',2200,'','',7) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('nissan-magnite','Nissan Magnite','Compact SUV','2023',5,2,'Petrol','Manual',2000,'','/images/cars/nissan-magnite.png',8) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('toyota-urban-cruiser','Toyota Urban Cruiser','Compact SUV','2022',5,2,'Petrol','Manual',2500,'','/images/cars/toyota-urban-cruiser.png',9) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('maruti-ertiga','Maruti Ertiga','MUV','2026',6,3,'CNG / Petrol','Manual',2500,'','/images/cars/maruti-ertiga.png',10) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('kia-carens','Kia Carens','MUV','2025',6,3,'Petrol','Manual',3000,'','/images/cars/kia-carens.png',11) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('kia-clavis','Kia Clavis','MUV','2025',6,3,'Diesel','Manual',3200,'','',12) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('toyota-innova-crysta','Toyota Innova Crysta','MUV','2026',7,3,'Diesel','Manual',3500,'','innova-crysta.jpg',13) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('toyota-innova-hycross','Toyota Innova Hycross','MUV','2025',7,3,'Strong Hybrid','Automatic',5500,'','/images/cars/toyota-innova-hycross.png',14) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mg-hector-plus','MG Hector Plus','SUV','2020',6,4,'Petrol','Manual',3500,'','',15) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('tata-safari','Tata Safari','SUV','2022',6,4,'Diesel','Manual',4000,'','/images/cars/tata-safari.png',16) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mahindra-scorpio-classic','Mahindra Scorpio Classic','SUV','2025',7,4,'Diesel','Manual',5000,'','/images/cars/mahindra-scorpio-classic.png',17) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mahindra-scorpio-n','Mahindra Scorpio N','SUV','2026',7,4,'Petrol','Automatic',5000,'','',18) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mahindra-xuv700','Mahindra XUV700','SUV','2024',7,4,'Petrol','Automatic',5500,'','',19) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mahindra-thar','Mahindra Thar','SUV','2025',4,4,'Diesel','Manual',5500,'New','thar.jpg',20) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('ford-endeavour','Ford Endeavour','SUV','2022',7,4,'Diesel','Automatic',10000,'','/images/cars/ford-endeavour.png',21) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('toyota-fortuner','Toyota Fortuner','SUV','2025',7,4,'Petrol','Automatic',9000,'Popular','fortuner.jpg',22) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('toyota-fortuner-legender','Toyota Fortuner Legender','SUV','2023',7,4,'Diesel','Automatic',10000,'','/images/cars/toyota-fortuner-legender.png',23) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('audi-a3','Audi A3','Luxury','2022',5,2,'Diesel','Automatic',13000,'','/images/cars/audi-a3.png',24) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('audi-a4','Audi A4','Luxury','2022',5,2,'Diesel','Automatic',14000,'','audi-a4.jpg',25) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('audi-a3-convertible','Audi A3 Convertible','Luxury','2023',4,2,'Petrol','Automatic',16000,'','/images/cars/audi-a3-convertible.png',26) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mercedes-c-class','Mercedes C-Class','Luxury','2023',5,2,'Petrol','Automatic',15000,'','',27) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mercedes-c-220','Mercedes C 220','Luxury','2020',5,2,'Diesel','Automatic',15000,'','',28) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mercedes-e-class','Mercedes E-Class','Luxury','2022',5,2,'Diesel','Automatic',15000,'','/images/cars/mercedes-e-class.png',29) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mercedes-glc-200','Mercedes GLC 200','Luxury','2023',5,2,'Petrol','Automatic',16000,'','',30) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mercedes-300-convertible','Mercedes 300 Convertible','Luxury','2023',4,2,'Petrol','Automatic',20000,'','/images/cars/mercedes-300-convertible.png',31) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('jaguar-xf','Jaguar XF','Luxury','2020',5,2,'Petrol','Automatic',16000,'','',32) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('bmw-5-series','BMW 5 Series','Luxury','2021',5,2,'Petrol','Automatic',18000,'','/images/cars/bmw-5-series.png',33) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('range-rover','Range Rover','Luxury','2021',5,2,'Petrol','Automatic',25000,'','',34) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('mercedes-g-wagon','Mercedes G-Wagon','Luxury','2024',5,2,'Petrol','Automatic',25000,'','',35) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('land-rover-defender','Land Rover Defender','Luxury','2026',5,2,'Diesel','Automatic',40000,'','',36) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('hummer','Hummer','Luxury','2020',5,2,'Petrol','Automatic',150000,'','',37) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('rolls-royce','Rolls Royce','Luxury','2024',4,2,'Petrol','Automatic',150000,'','',38) on conflict (slug) do nothing;
insert into cars (slug,name,category,model_year,seats,luggage,fuel,transmission,price,badge,photo_url,sort_order) values ('vintage-wedding-car','Vintage Wedding Car','Luxury','1950',4,2,'Petrol','Manual',20000,'','',39) on conflict (slug) do nothing;

-- ===== CONTENT =====
insert into content (key,value) values ('hero','{"eyebrow": "10 Years \u00b7 24/7", "title": "Your ride is ready when you are.", "subtitle": "Cabs, self-drive cars, luxury sedans and group coaches across Delhi NCR, Goa and Jewar Airport \u2014 booked in seconds on WhatsApp.", "image": "/images/site/hero.jpg"}'::jsonb) on conflict (key) do update set value=excluded.value;
insert into content (key,value) values ('whatsapp','{"primary": "917522817555", "jewar": "919953599735"}'::jsonb) on conflict (key) do update set value=excluded.value;
insert into content (key,value) values ('stats','[{"num": "500+", "label": "Taxis in fleet"}, {"num": "900+", "label": "Happy clients"}, {"num": "700+", "label": "Verified drivers"}, {"num": "1800+", "label": "Trips done"}]'::jsonb) on conflict (key) do update set value=excluded.value;
insert into content (key,value) values ('offices','[{"city": "Noida Extension", "address": "SF-133, Galaxy Diamond Plaza, Gaur City-1, Sector-4, Greater Noida West \u2013 201308"}, {"city": "Ghaziabad", "address": "1, JC4J+JM, Ghaziabad, Uttar Pradesh \u2013 201016"}, {"city": "Gurgaon", "address": "C-4 206, PWO Apartments, Sector-43, Gurugram, Haryana \u2013 122009"}, {"city": "Goa", "address": "MM Travels, H.No-66, Bogda, Vasco Da Gama, Goa \u2013 403802"}, {"city": "Jewar", "address": "Front of primary school, Kishorpur, Uttar Pradesh \u2013 203135"}, {"city": "Noida", "address": "A-152, Sector 63 Rd, A Block, Sector 63, Noida, UP \u2013 201309"}]'::jsonb) on conflict (key) do update set value=excluded.value;
insert into content (key,value) values ('phones','[["Noida", "917522817555"], ["Noida Ext.", "917522817555"], ["Ghaziabad", "917522817555"], ["Gurgaon", "918368737081"], ["Meerut", "919108617014"], ["Goa", "919108617014"], ["Jewar Airport", "919953599735"]]'::jsonb) on conflict (key) do update set value=excluded.value;

-- ===== BLOG =====
insert into blog_posts (slug,title,excerpt,body,published) values ('trusted-travel-partner-delhi-ncr','Your Trusted Travel Partner in Delhi NCR','From daily commutes to weddings and airport runs, here''s how Grab Your Cab keeps Delhi NCR moving.','From daily commutes to weddings and airport runs, here''s how Grab Your Cab keeps Delhi NCR moving. Full article body goes here — edit in the admin panel.',true) on conflict (slug) do nothing;
insert into blog_posts (slug,title,excerpt,body,published) values ('self-drive-cars-for-every-trip','Self Drive Cars for Every Trip','Freedom to drive on your own terms — a quick guide to renting a self-drive car.','Freedom to drive on your own terms — a quick guide to renting a self-drive car. Full article body goes here — edit in the admin panel.',true) on conflict (slug) do nothing;
insert into blog_posts (slug,title,excerpt,body,published) values ('reliable-corporate-travel-solutions','Reliable Corporate Travel Solutions','Employee transport, client pickups and airport transfers with billing you can rely on.','Employee transport, client pickups and airport transfers with billing you can rely on. Full article body goes here — edit in the admin panel.',true) on conflict (slug) do nothing;
