import type { MetadataRoute } from "next";

const BASE_URL = "https://www.grabyourcab.com";

const urls = [
  "/",
  "/taxi-service-delhi",
  "/self-drive-car-rental-delhi",
  "/cab-service-gurgaon",
  "/self-drive-car-rental-gurgaon",
  "/cab-service-noida",
  "/self-drive-car-rental-noida",
  "/taxi-service-greater-noida",
  "/jewar-airport-cab-service",
  "/taxi-service-ghaziabad",
  "/car-rent-faridabad",
  "/taxi-service-meerut",
  "/car-rental-goa",
  "/tempo-traveller-rent",
  "/luxury-car-rental",
  "/corporate-cab-services",
  "/about-us",
  "/contact",
  "/cars/maruti-wagon-r",
  "/cars/maruti-celerio",
  "/cars/maruti-swift-dzire",
  "/cars/hyundai-aura",
  "/cars/honda-city",
  "/cars/toyota-corolla-altis",
  "/cars/tata-nexon",
  "/cars/maruti-brezza",
  "/fleet",
  "/taxi-service-delhi-ncr",
  "/self-drive-car-rental-delhi-ncr",
  "/luxury-cars-on-rent-delhi-ncr",
  "/tempo-travellers-delhi-ncr",
  "/luxury-bus-delhi-ncr",
  "/special-customized-delhi-ncr",
  "/corporate-taxi-car-rental-delhi-ncr",
  "/delhi-ncr",
  "/goa",
  "/noida-international-airport-jewar",
  "/cars/nissan-magnite",
  "/cars/toyota-urban-cruiser",
  "/taxi-service-goa",
  "/taxi-service-noida-international-airport-jewar",
  "/self-drive-car-rental-goa",
  "/self-drive-car-rental-noida-international-airport-jewar",
  "/cars/audi-a3",
  "/cars/audi-a4",
  "/cars/audi-a3-convertible",
  "/cars/mercedes-c-class",
  "/cars/mercedes-c-220",
  "/cars/mercedes-e-class",
  "/luxury-cars-on-rent-goa",
  "/luxury-cars-on-rent-noida-international-airport-jewar",
  "/tempo-travellers-goa",
  "/tempo-travellers-noida-international-airport-jewar",
  "/luxury-bus-goa",
  "/luxury-bus-noida-international-airport-jewar",
  "/special-customized-goa",
  "/special-customized-noida-international-airport-jewar",
  "/corporate-taxi-car-rental-goa",
  "/corporate-taxi-car-rental-noida-international-airport-jewar",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return urls.map((path) => ({
    url: `${BASE_URL}${path}`,
    lastModified: new Date("2026-09-28"),
  }));
}